### PR TITLE
extend cdd header search to include $PATH/../include/cdd

### PR DESCRIPTION
**Pull request by barcode**

### CODE REVIEW

**Comment by vsamy** [comment]
That's a good idea. But why adding so many paths?
Especially, paths like "PATH" are more suitable for global system path rather than begin specific to cdd.

Could you modify this so you can pass directly a specific variable in the cmake command?
For example, one could type:
cmake -DCDD_HINT_PATH=<the_path>
and then this value is given to the find_library macro.
You can put the cdd default installation path as default value.

Please update the readme too. :)

**Comment by barcode** [comment]
> Especially, paths like "PATH" are more suitable for global system path rather than begin specific to cdd.

exactly this is the reason why i use PATH.
If you have a local install directory, you will probably have added it to PATH (how are you going to use it otherwise?).
Hence there would be no need to mess around with additional cmake parameters (which you, or at least i, will forget one day when running cmake).

i think it is more clean to just run cmake and let it search the path (what is part of the reason to use cmake) instead of searching the path as human and pass it to cmake.

also i don't see a real problem with adding "so many paths" since this does not really take long and is not runtime relevant in any way.

such a flag could be used as an additional way to provide this path in case you did not add your local install directory to path.

**Comment by vsamy** [comment]
> how are you going to use it otherwise?

PATH is system global. Why would I add cdd path to the global path? 
In PATH i have my bin/ directory to access soft from anywhere, but cdd is not a soft. PATH should not be used for libs but for executables and scripts. The convention are given [here](https://en.wikipedia.org/wiki/Environment_variable#Unix_2) and [here](https://en.wikipedia.org/wiki/PATH_(variable)).

> I don't see a real problem with adding "so many paths" since this does not really take long and is not runtime relevant in any way.

It is not about performance. Adding all global paths is just not clean. So, one can put his cdd path in default path or PATH or ENV or PATHS or...
Also, PATHS, ENV and PATH_SUFFIXES are not defaulted environment variable, if you add those you should add every user-defined variables.

Normally, if you have installed a library in a specific directory, you should have it in the LD_LIBRARY_PATH.

**Comment by barcode** [comment]
ok maybe what i wrote was a bit unclear.
a local install dir normally contains the following folders:
- bin  -> for executables (added to PATH)
- etc -> other 
- include -> headers
- lib -> for libs (added to LD_LIBRARY_PATH)
- share -> doc etc

there is no env var i know for include dirs (ok there are gcc specific vars e.g. C_INCLUDE_PATH)

> PATH is system global. 

it is just an env var. i  add local installdirs (to be exact the bin dir) in my `.profile`
so there is no need to change the global PATH variable

> PATH should not be used for libs but for executables

i know. i am not adding path to the searchdirs but `PATH/../include/cdd`

> Also, PATHS, ENV and PATH_SUFFIXES are not defaulted environment variable, if you add those you should add every user-defined variables.

they are no environment variables but [cmake keywords for find](https://cmake.org/cmake/help/v3.0/command/find_path.html)!
PATHS -> no i list searchpaths
ENV -> the following are env vars containing colon seperated directories
PATH_SUFFIXES -> append these suffixes to the given paths and search in the resulting directory

> Normally, if you have installed a library in a specific directory, you should have it in the LD_LIBRARY_PATH.

but this is about the include dir.
since there is no default variable for include dir, i have to use a relative path.
this relative path could also use LD_LIBRARY_PATH as base instead of PATH.
I chose PATH/../include since it covers /usr/include and /usr/local/include (per default LD_LIBRARY_PATH is empty).

**Comment by vsamy** [comment]
Ok i got you now. :)
Sorry I don't you find_package very often.

**Pull request merged**
