### PR TITLE
Error handling and dd_NumericallyInconsistent test

### PR DESCRIPTION
**Pull request by stephane-caron**
This tiny PR reports more details on cdd errors to the user. It also adds a test for a runtime error (dd_NumericallyInconsistent) that I encountered in practice. Please check that this test is reproducible on your machine, as its values may be specific to my architecture somehow.

### CODE REVIEW

**Comment by vsamy** [comment]
I agree, we should not just throw an exception and we should output a proper message.
Though, do to it properly, I think we need to output a comprehensible message.

Function `setHrep`, `setVrep`, `setRays` and `setVertices`, should return a `bool` to inform whether or not the operation succeed.
Then, if asked by the user, the lib should add a function like `lastErrorMessage()` that return an std::string (or const char*) that explains the receiving error.

I don't really like to output messages like "dd_NotAvailForH", it is not clear what is dd, what is not available for H, and what is H. I don't even know when this error can occur. So the function should return information to make the user understand what is wrong.

**Comment by vsamy** [comment]
The best is to use error message from cddlib.
You can get detailed information in file `cddio.c` line `1644`

https://github.com/cddlib/cddlib/blob/dc8155547f9897004f8729cf8a3cb123c53f07d8/lib-src/cddio.c#L1644

Please use these information

**Comment by vsamy** [comment]
Also, I can not accept your test.
This is an architecture-related problem. I have test it on my machine and the test fails, no exception is thrown. Please remove it, or make it passable.

**Comment by vsamy** [comment]
Wow, sorry for the very late answer! I completely forgot about this.

Well, first thank you, it's a good enhancement for the lib.
There is one thing I would to change though. Even if cdd is difficult to install on Windows it can be done and as Eigen is cross-platform I would like to keep this lib cross-platform too. 

So the `constexpr char TMP_FPATH[] = "/tmp/dd_lastErrorMessage"; ` is unfortunate.
Also, we should not save any file, it is a bit overkill to have a log file for one message. Therefore, Since cdd is using `printf` function I suggest to use temporary file: http://www.cplusplus.com/reference/cstdio/tmpfile/
Thus the file will be deleted at the end of the program or when we close it.

Then you could just get what is in the file by doing something like:
```
dd_WriteErrorMessages(tmpFile, err_);
if(fseek(tmpFile, 0, SEEK_SET) != 0)
  return "Cannot get last error message: unable to get data fromtemporary file"; 
char* buffer = char[200];
size_t nChar = fread(buffer, sizeof(char), size_t(-1), tmpFile);
// You can check that eof is reached using feof
std::string strError(buffer, nChar);
delete[] buffer;
fclose(tmpFile); // Destroy the file
return strError;
```

**Comment by stephane-caron** [comment]
Thanks for your feedback and the ``tmpfile`` snippet. I integrated it in the latest commit.

**Comment by vsamy** [comment]
Perfect :)

**Pull request merged**
