### PR TITLE
Memory Leak  ddfMatrix2EigenMatrix function()

### PR DESCRIPTION
**Pull request by philip-long**
Hi all,

First, thanks for this great library ! 

As I have been using it lately, I noticed a memory leak which I tracked down, using valgrind  to Polyhedron::ddfMatrix2EigenMatrix. To resolve this issue I added a delete matrix line. It seems like the mat should be deleted anyway in the destructor but its not, I don't really understand why.  

I'm attaching the two valgrind outputs, pre change and post change for info. 

[ValgrindOutput_post.txt](https://github.com/vsamy/eigen-cddlib/files/2389509/ValgrindOutput_post.txt)
[ValgrindOutput_Pre.txt](https://github.com/vsamy/eigen-cddlib/files/2389510/ValgrindOutput_Pre.txt)

### CODE REVIEW

**Comment by vsamy** [comment]
Thank you for using my libs :)
I am glad to hear that it is useful to someone haha.

You unfortunately added your build folder in the commits. Could you delete all the build folder please?

So, I guess you are right on the memory leak. `mat` is indeed never deleted. thx :)

Last thing, I can not accept the modification on the `initializeMatrixPtr` function.`Eigen::Matrix<int, 1, 1>::Index ` is deprecated since Eigen 3.3, you either need to upgrade your Eigen, or i can accept an aliasing of Eigen Index when a version lower than the 3.3 is found.

**Comment by vsamy** [comment]
Neither gdb nor boost detects any memory leaks on the tests. Could you send me or happen a test that triggers a memory leak detection?

**Comment by philip-long** [comment]
I deleted the build files in the second commit, sorry about the confusion. As for the Eigen Index. yes I'll fix it and re-commit. 

 I believe I tried gdb and it didn't find anything, I noticed the initial problem as the process memory was increasing during execution eventually crashing the program, but perhaps I'm misusing the library.  I'm launch the file as a ros node with the following launch prefix. 

`
launch-prefix="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes"
`

[tests.txt](https://github.com/vsamy/eigen-cddlib/files/2397764/tests.txt)

**Comment by philip-long** [comment]
I deleted the build files in the second commit, sorry about the confusion. As for the Eigen Index. yes I'll fix it and re-commit. 

 I believe I tried gdb and it didn't find anything, I noticed the initial problem as the process memory was increasing during execution eventually crashing the program, but perhaps I'm misusing the library.  I'm launch the file as a ros node with the following launch prefix. 

`
launch-prefix="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes"
`

[tests.txt](https://github.com/vsamy/eigen-cddlib/files/2397778/tests.txt)

**Comment by philip-long** [comment]
In fact I can do a whole new pull request if that's better?

**Pull request closed without merging**
